### PR TITLE
Added missing id getters

### PR DESCRIPTION
**Pull request by core23**
### Changelog

``` markdown
### Added
- Added missing `CategoryInterface::getId` method
- Added missing `CollectionInterface::getId` method
- Added missing `TagInterface::getId` method
```
### Subject

Added missing id getters to model classes
### To do
- [x] Add an upgrade note

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
As said in previous PR, adding methods to interfaces is BC break.

**Comment by OskarStark** [comment]
Please add an UPGRADE notice @core23

**Comment by Soullivaneuh** [comment]
@OskarStark Please not this PR can not be merged not because `master` is about `2.4.x-dev` actually.

**Comment by OskarStark** [comment]
I know, but when we will merge this PR in the future for 3.0, e need an UPGRADE notice, right?

**Comment by Soullivaneuh** [comment]
ofc

**Comment by OskarStark** [comment]
sorry, but what does ``ofc``mean?

**Comment by Soullivaneuh** [comment]
ofc = OF Course. :-)

**Comment by OskarStark** [comment]
:+1:  :)

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by core23** [comment]
This is a major change

**Comment by Soullivaneuh** [comment]
Sorry @core23 

Please add a changelog note on the PR body.

**Comment by core23** [comment]
Finished @Soullivaneuh

**Comment by OskarStark** [comment]
i restarted travis, but there were some dependency problems

**Comment by core23** [comment]
Not releated to this :/

@Soullivaneuh Can you help with the dependencies?

**Comment by Soullivaneuh** [comment]
Still have to look at this...

**Comment by greg0ire** [comment]
Thanks @core23 ! Can you make the changelog fit on oneline?

**Comment by core23** [comment]
Fixed that

**Pull request merged**
