### PR TITLE
Fix the creation of a new context

### PR DESCRIPTION
**Pull request by jerome-fix**
## Subject

I am targeting this branch, because it's a bug introduced on this [commit](https://github.com/sonata-project/SonataClassificationBundle/commit/ae001e0928c83236343319e1610512bad73f43a2) 

A new context is created... if it already exists. It is the opposite that should be done.

 

## Changelog

```markdown
### Fixed
- Create a new context only if it does not exist
```

### CODE REVIEW

**Comment by jerome-fix** [comment]
@VincentLanglet 

Into this file the comparison with NULL is systematically done instead of testing that the variable is an instance of the expected class. Is this a general choice for Sonata? If yes I can modify my RP in this sense.

`null === $context`  vs. `!$context instanceof ContextInterface `

Jérôme.

**Comment by jordisala1991** [comment]
To me in this case is easier to read with null === $context, instead of seeing the ! on the `!$context instanceof ContextInterface` expression.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> To me in this case is easier to read with null === $context, instead of seeing the ! on the `!$context instanceof ContextInterface` expression.

I agree.

When I see `$foo instanceof Foo` it makes me believe that $foo could be either instance of Foo or instanceof Bar.
For something Foo|null, I always pref to check null instead.

**Comment by jerome-fix** [comment]
@VincentLanglet @jordisala1991 

I changed the PR. No opinion on the form, I do with the conventions of the project.

Jérôme

**Comment by jerome-fix** [comment]
Hi,

Do you plan to publish this correction soon?

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @jerome-fix . Not sure when I can do the release, will try to do it later today.

**Comment by jerome-fix** [comment]
Thanks @jordisala1991

**Comment by VincentLanglet** [comment]
On it https://github.com/sonata-project/SonataClassificationBundle/pull/839

**Pull request merged**
