### PR TITLE
Fixed missing properties in models

### PR DESCRIPTION
**Pull request by RewoDevNull**
Added slug property to context.php and count property to category.php for fixing issue #174.

### CODE REVIEW

**Comment by RewoDevNull** [comment]
Waiting for merge. Ping @core23

**Comment by core23** [comment]
Please squash your commits

**Comment by core23** [comment]
I think this is the wrong approach for the bug. We don't use these properties anywhere.

**Comment by webdevilopers** [comment]
The `slug` property indeed is used inside the mapping for ORM AND ODM:
https://github.com/sonata-project/SonataClassificationBundle/blob/master/Resources/config/doctrine/BaseCategory.orm.xml#L8

But the `count` is only set for ODM:
https://github.com/sonata-project/SonataClassificationBundle/blob/master/Resources/config/doctrine/BaseCategory.mongodb.xml#L14

**Comment by core23** [comment]
Yes, they were declared in the xml files, but we don't use them anywhere. IMO we should remove them form the xml files. @webdevilopers

**Comment by webdevilopers** [comment]
@RewoDevNull Can you update your composer to current `dev-master`? The `slug` property officially works.
And then add a PR that removes the `count` property from all mappings?

That should fix #174.

**Comment by RewoDevNull** [comment]
Yep is done @core23. 
Removed the previous changes from Context and Category.
And removed the count property from BaseCategory.mongodb.xml and the slug property from BaseContext.mongodb.xml.

I had to remove the slug property cause of "composer update" error: 

`[RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
    [Doctrine\ODM\MongoDB\Mapping\MappingException]                          
    An error occurred in Sonata\ClassificationBundle\Document\BaseContext    
                                                                             
                                                                             
    [ReflectionException]                                                    
    Property slug does not exist`

After i removed the slug property from config-file i got the count property error. 
This fixed this issue (#174) and additionally my issue (see above).

**Comment by greg0ire** [comment]
Please run `make cs` to keep tests green.

**Comment by RewoDevNull** [comment]
Yep, all passed.

**Comment by greg0ire** [comment]
Ok now, please squash all four commits into one commit.

**Comment by RewoDevNull** [comment]
I will do the changes again and make a new PR. 
My local git makes some trouble.

**Comment by greg0ire** [comment]
We're here to help if you have trouble using git.

**Comment by RewoDevNull** [comment]
Yea my local git shot down my forked branch by rebasing. 
I started a new PR (#176) and do it from the beginning right. ;-)
Thanks for help.

**Pull request closed without merging**
