### PR TITLE
Add translation for "breadcrumb.link_category_tree"

### PR DESCRIPTION
**Pull request by stphnpt**
add ``breadcrumb.link_category_tree`` and update ``filter.label_name``

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Please make a better title and commit comment according to your modification.

**Comment by stphnpt** [comment]
@Soullivaneuh Hi ! Could you help me understand what I have to do/correct here to insure the travis-ci doesn't fail ?

**Comment by OskarStark** [comment]
I restarted travis, lets see if it work

**Comment by OskarStark** [comment]
please use this as your commit message:

```
Add french translation for "breadcrumb.link_category_tree" and update "filter.label_name"
```

you can use ```git commit --amend`` and the ``git push --force`` to update this PR

**Comment by core23** [comment]
Thank you @stphnpt

**Pull request merged**
