### PR TITLE
Don't hide the field ID when create a new context

### LINKED ISSUE #106: Unable to create new Context from Admin

### PR DESCRIPTION
**Pull request by jerome-fix**
fixes #106

### CODE REVIEW

**Comment by kamilZ** [comment]
+1 works like a charm

**Comment by ppetermann** [comment]
this will always show the id field, which wasn't intended in the original code (and i *guess*) could cause problems when editing (as the id shouldn't be changed ;)

**Comment by core23** [comment]
Please rebase @jerome-fix

**Comment by OskarStark** [comment]
we cant merge this you are not allowed to change the ID later :-1:

**Pull request closed without merging**
