### PR TITLE
Added missing getId method to Context model

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is a patch.

```markdown
### Added
- Added `Context::getId` method
```

## Subject

There is already a `setId` method, but the getter was missing.

### CODE REVIEW

**Comment by greg0ire** [comment]
Not sure it was overlooked, maybe it is never needed?

**Comment by core23** [comment]
The method exists in the interface... https://github.com/sonata-project/SonataClassificationBundle/blob/eaf69f12198a56a8edcf18b1e8557ea208de4364/src/Model/ContextInterface.php#L58

**Comment by jordisala1991** [comment]
I think this happens on all sonata entities. And it is an abstract class, so when you extend it you normally add the method. Not saying not to this PR but reconsider if it is really needed, or why it wasnt there

**Comment by core23** [comment]
Yes, it's an abstract class, but all methods (except this one) is implemented, even the setter method.

**Comment by core23** [comment]
Please review @jordisala1991

**Comment by jordisala1991** [comment]
Already did, I am not sure why do we need this method. It was approved by @soullivaneuh and @greg0ire , so they can merge it if they want.

**Comment by greg0ire** [comment]
I think this is a sensible implementation.

**Pull request merged**
