### PR TITLE
Allow Support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Add support for PHP 8.x
```

### CODE REVIEW

**Comment by Yozhef** [comment]
Block By https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1285

**Comment by jordisala1991** [comment]
This is no longer blocked

**Comment by VincentLanglet** [comment]
Blocked by sonata-project/media-bundle

**Comment by jordisala1991** [comment]
media-bundle is still not released, we need to fix: 

https://github.com/sonata-project/SonataMediaBundle/pull/1944#discussion_r601085479
https://github.com/sonata-project/SonataMediaBundle/pull/1943

**Comment by Yozhef** [comment]
@jordisala1991 maybe I drop imagine 0.7? in dev kit?

**Comment by jordisala1991** [comment]
Yes, please, that would be nice :)

**Comment by phansys** [comment]
For the changelog, please note that you are adding support for PHP `8.x`, not just `8.0`.

**Review by jordisala1991 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]
Will wait for https://github.com/sonata-project/dev-kit/pull/1386

**Review by wbloszyk — APPROVED** [review]

**Pull request merged**
