### PR TITLE
Added sortable option to admins

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
restarted travis...

**Comment by OskarStark** [comment]
again a timeout... can you help @Soullivaneuh

**Comment by Alexandre-T** [comment]
No luck, the travis.yml was updated 14h ago !
The line to change is :
`- travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS`
The line which fixes :
`- travis_wait 40 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS`
This is only a small patch, it is not the better way to solve this issue. It is better than nothing, but not much! ;-)

**Comment by core23** [comment]
Can you help? @Soullivaneuh

**Comment by core23** [comment]
ping @OskarStark

**Comment by OskarStark** [comment]
thank you @core23

**Pull request merged**
