### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by core23**
Manual merge of 3.x into the master branch.

Refs sonata-project/dev-kit#221

### CODE REVIEW

**Comment by greg0ire** [comment]
> sonata-project/media-bundle dev-master conflicts with sonata-project/classification-bundle[4.x-dev].

Hmmm what?

**Comment by core23** [comment]
Will be fixed after merging https://github.com/sonata-project/SonataClassificationBundle/pull/196

**Comment by jordisala1991** [comment]
This does not make sense anymore right?

**Comment by greg0ire** [comment]
Oh, right, didn't notice this PR, sorry @core23 !

**Comment by core23** [comment]
No problem, this was an old one ;)

**Pull request closed without merging**
