### PR TITLE
Replace the global symfony dependency by only necessary components

### PR DESCRIPTION
**Pull request by Th3Mouk**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by Th3Mouk** [comment]
@Soullivaneuh this one too

**Comment by Soullivaneuh** [comment]
Please reopen it agains 3.x branch, not master.

**Comment by core23** [comment]
Isn't it a BC break? @Soullivaneuh

**Comment by Soullivaneuh** [comment]
@core23 Why it should be? The dependencies are still good for the bundle and we can't be responsible if some user use libraries without importing them on their root projects.

**Comment by Th3Mouk** [comment]
i know but if a push again the bot will not crawl the PR isn't ? I was thinking the issue must be open before rebase sorry

**Comment by Soullivaneuh** [comment]
@Th3Mouk You can't change the target branch on the same PR.

https://github.com/isaacs/github/issues/18

**Pull request closed without merging**
