### PR TITLE
code formatted

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
PR need a rebase to make Travis green.

**Comment by OskarStark** [comment]
rebase done @Soullivaneuh

**Comment by Soullivaneuh** [comment]
:+1: I let you merge it when Travis will be green.

**Comment by OskarStark** [comment]
@Soullivaneuh can you please check travis? restarted this build twice, but a timeout occured.... :(

Thank you!

**Comment by Soullivaneuh** [comment]
Ignore this Travis case, it's buggy.

**Comment by OskarStark** [comment]
thank you!

**Pull request merged**
