### PR TITLE
Add manager aliases

### PR DESCRIPTION
**Pull request by core23**
## Subject

Add public aliases to all manager interface so that they can be used with DI.

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Add public aliases to all manager interface
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I haven't declared a service in a long time, but for what I remembered they recommend class as id.

Shouldn't we start using the new service declaration syntax `Sonata\ClassificationBundle\Model\ContextManager` instead of
`sonata.classification.manager.context` for all the Sonata services ?

**Comment by core23** [comment]
> Shouldn't we start using the new service declaration syntax `Sonata\ClassificationBundle\Model\ContextManager` instead of
> `sonata.classification.manager.context` for all the Sonata services ?

We can't change this with a minor release, but we should not named ids with the next major(s).

**Comment by VincentLanglet** [comment]
> We can't change this with a minor release, but we should not named ids with the next major(s).

I agree. Since the 4.x is already hard to get, should we plan this for 5.x instead ?
What's the best to plan things for all the project ? Should I create an issue in every project ?

**Comment by core23** [comment]
I would not plan to far. We try to release new major for nearly two years...

**Comment by VincentLanglet** [comment]
> I would not plan to far. We try to release new major for nearly two years...

I don't understand. That's why I try to not add more work in the 4.x release and was thinking that this not necessary change could wait for the next one.
And I'll hope we'll succeed in making major release at least every year after the 4.x 😄

**Comment by core23** [comment]
> I don't understand. That's why I try to not add more work in the 4.x release and was thinking that this not necessary change could wait for the next one.

Let's move this discussion to slack. Hopefully I can help with the next steps on Friday when I got my day off.

**Pull request merged**
