### PR TITLE
Fixed missing properties in models

### PR DESCRIPTION
**Pull request by RewoDevNull**
Completed fix for Issue #174.
Now i got it. ;-)

### CODE REVIEW

**Comment by greg0ire** [comment]
Can you please reword your commit like this : 

```
Remove obsolete properties from the ODM model

Fixes #174
Explain here why and how this fixes the bug
```

**Comment by RewoDevNull** [comment]
Finally i got it.

**Comment by greg0ire** [comment]
Not really, sorry.

The commit message should explain clearly what was the bug, and how what you did solved it. After reading a bit of #175 , I see that @core23 asks you to remove one property, not two, that's why I'm asking that. Your commit messages should read exactly like that.

```
explain what you did
leave a blank line here
Optionally add : "Fixes <issue number>"
And then explain us your commit like we are five
```

We don't really want to merge what we do not fully understand, and we are very dumb, sorry.

**Comment by greg0ire** [comment]
Way better :)

**Comment by greg0ire** [comment]
@webdevilopers can you check ? Should both properties be removed or just one ?

**Comment by greg0ire** [comment]
@RewoDevNull : more info on proper commit messages : http://rakeroutes.com/blog/deliberate-git/

**Comment by RewoDevNull** [comment]
:+1:

**Comment by webdevilopers** [comment]
Coming from the original issue https://github.com/sonata-project/SonataClassificationBundle/issues/174#issuecomment-188226351 I only had problems with `count` in `dev-master`.
I think @RewoDevNull switched to an earlier commit lately that's why he is also experiencing problems with `slug`.

Can you check with current `dev-master` otherwise too @RewoDevNull ?

**Comment by RewoDevNull** [comment]
So i got two errors.
The first error was the missing `slug` property. 
```bash
> php /usr/local/bin/composer.phar update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing sonata-project/classification-bundle (dev-master d50ec08)
    Cloning d50ec088961e59096ca970686c799922218935c0

  - Updating sonata-project/admin-bundle dev-master (7533a89 => 44f8162)
    Checking out 44f8162fb76f2b1ffbfce710102d02f0bb5d278b

Writing lock file
Generating autoload files
Compiling component files
> ComponentInstaller\Installer::postAutoloadDump
Updating the "app/config/parameters.yml" file
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
                                            
  [Doctrine\ODM\MongoDB\Mapping\MappingException]                        
  An error occurred in Sonata\ClassificationBundle\Document\BaseContext  
  
  [ReflectionException]         
  Property slug does not exist  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
                                                           
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
    [Doctrine\ODM\MongoDB\Mapping\MappingException]                          
    An error occurred in Sonata\ClassificationBundle\Document\BaseContext    
                                                          
    [ReflectionException]                                                    
    Property slug does not exist                                             
                                                                     
```

After fixing the error by removing `<field name="slug" type="string" fieldName="slug" />` in BaseContext.mongodb.xml i got the missing `count` property error. 

```bash
> php /usr/local/bin/composer.phar update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
Compiling component files
> ComponentInstaller\Installer::postAutoloadDump
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
                                              
  [Doctrine\ODM\MongoDB\Mapping\MappingException]                         
  An error occurred in Sonata\ClassificationBundle\Document\BaseCategory  
 
  [ReflectionException]          
  Property count does not exist  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
                                       
  [RuntimeException]                                                          
  An error occurred when executing the "'cache:clear --no-warmup'" command:   

    [Doctrine\ODM\MongoDB\Mapping\MappingException]                           
    An error occurred in Sonata\ClassificationBundle\Document\BaseCategory    

    [ReflectionException]                                                     
    Property count does not exist
```

After i fixed this all works fine for me. 

This was in the current `dev-master`.
This is my `composer.json`:

>"sonata-project/doctrine-orm-admin-bundle": "dev-master",
>"sonata-project/cache-bundle": "dev-master",
>"sonata-project/classification-bundle": "dev-master",
>"sonata-project/datagrid-bundle": "dev-master",
>"sonata-project/user-bundle": "dev-master",

So i can't do any `composer update` without fixing the `missing $slug property` error.

**Comment by greg0ire** [comment]
@webdevilopers : I think @RewoDevNull is up-to-date with the master branch of this bundle, don't you?

**Comment by webdevilopers** [comment]
Can you post your composer.lock part of the classification bundle too @RewoDevNull?

**Comment by core23** [comment]
Looks okay to me, but is sadly a BC break :/

**Comment by webdevilopers** [comment]
I removed `composer.lock` and the vendor dir for the bundle and updated. This is the commit I use:
```javascript
            "name": "sonata-project/classification-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/sonata-project/SonataClassificationBundle.git",
                "reference": "d50ec088961e59096ca970686c799922218935c0"
            },
```
And it only returns: **Property count does not exist**

**Comment by RewoDevNull** [comment]
I removed my `vendor` directory and the `composer.lock` and still got the same 2 errors. 

This is my composer.lock:

```bash
 {
            "name": "sonata-project/classification-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/sonata-project/SonataClassificationBundle.git",
                "reference": "d50ec088961e59096ca970686c799922218935c0"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/sonata-project/SonataClassificationBundle/zipball/d50ec088961e59096ca970686c799922218935c0",
                "reference": "d50ec088961e59096ca970686c799922218935c0",
                "shasum": ""
            },
            "require": {
                "sonata-project/admin-bundle": "~2.4",
                "sonata-project/datagrid-bundle": "~2.2",
                "sonata-project/doctrine-orm-admin-bundle": "~2.4",
                "symfony/form": "~2.3|~3.0",
                "symfony/framework-bundle": "~2.3|~3.0"
            },
```

I don't get it why i got these two errors and you only the second. 
I'm using the same commit version of this classification bundle as you.

**Comment by webdevilopers** [comment]
Do we have a 3rd person to test this? :)

Maybe @core23 can comment on this, looks like he knows if any of the properties are actually used:
https://github.com/sonata-project/SonataClassificationBundle/pull/175#issuecomment-188384851

**Comment by core23** [comment]
It isn't used by anything in this bundle, but it could be used by someone who extends this bundle. So we can't remove this in the 2.x branch.

**Comment by gnorby88** [comment]
I just updated sf 2.7.9 to 2.7.10 and i got same error. The slug and the count proterty is missing in the Model. The bundle isn't use these properties.. So why need it? If someone use these properties in own bundle, then define own mongo config file with these properties and thats it. No?

**Comment by core23** [comment]
@greg0ire @OskarStark  What do you think?

If we are strict on SemVer this is BC break, because we remove stuff. Altough we don't use this properties.

**Comment by greg0ire** [comment]
So it boils down to being BC vs fixing a bug, is that it? If it's unclear what people might actually be affected by the BC, I vote "fix the bug", because the bug is know to actually exist.

**Comment by core23** [comment]
:+1: for removing this

If we don't wan't to remove this, we could fix this the other way be adding the missing properties to the **BateCategory** and **BaseContext** model.

**Comment by core23** [comment]
@Soullivaneuh Can you have a look at this.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
