### PR TITLE
Applied fixes from FlintCI

### PR DESCRIPTION
**Pull request by soullivaneuh**

### CODE REVIEW

**Comment by OskarStark** [comment]
Ping @sonata-project/contributors

**Comment by franmomu** [comment]
> Ping @sonata-project/contributors

I messed up with the merge pushing directly to the upstream branch (not intended) and then trying to fix it 😞 if someone can help with https://github.com/sonata-project/SonataClassificationBundle/pull/548

**Comment by VincentLanglet** [comment]
@sonata-project/contributors should we disable this hook ? There is already a github action with a linter, isnt it ?

**Comment by phansys** [comment]
@VincentLanglet, see https://github.com/sonata-project/dev-kit/pull/836#discussion_r478899982.

**Pull request closed without merging**
