### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by franmomu**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@franmomu Test are failing

**Comment by franmomu** [comment]
> @franmomu Test are failing

Yup, that's why I marked the PR as draft, I have to take a look because at first sight I have no idea, maybe @wbloszyk can help?

**Comment by franmomu** [comment]
Looks like they were already failing in the previous merge https://github.com/sonata-project/SonataClassificationBundle/pull/546, somehow `->scalarNode('media')->defaultNull()->end()` this line disappeared in `Configuration.php`.

**Comment by greg0ire** [comment]
>  but maybe "media" support was removed in master

See #196

**Comment by franmomu** [comment]
Sorry, I executed `git push` instead of pushing it to my own branch 🤦, I've reverted the commits.

**Comment by franmomu** [comment]
Definitely I shouldn't have to make these changes at this hour and especially don't push on the branch 🤦

As can be seen in https://github.com/sonata-project/SonataClassificationBundle/commits/master, I reverted the wrong commit, instead of reverting 0600bdcde0cf03a78ee46d1c9ea949fe5c91873d I reverted 42e48b92cb3f4b98828e12a325893ca5e920a432.

I'd rather don't mess up more... @greg0ire can you please help here? sorry for the mess 😞

**Comment by greg0ire** [comment]
I don't understand exactly what was wrong but force pushed master to back to a080876, so before any of your commits from 10 hours ago, you can start over.

**Comment by franmomu** [comment]
> I don't understand exactly what was wrong but force pushed master to back to [a080876](https://github.com/sonata-project/SonataClassificationBundle/commit/a080876801b56a2ea297e7fc80dce030657d4016), so before any of your commits from 10 hours ago, you can start over.

Thanks! 👍  test didn't pass, it was unfinished.

**Pull request merged**
