### PR TITLE
Entity names in Advanced_configuration doc

### PR DESCRIPTION
**Pull request by stphnpt**
Update of entity names (context / media) in Advanced_configuration.rst

### CODE REVIEW

**Comment by core23** [comment]
Can you please rebase @stphnpt

**Comment by stphnpt** [comment]
I don't understand what I shall rebase ? It's a PR on master. How can I see the conflicts ??

**Comment by core23** [comment]
Your branch is out of date, please rebase this so we can merge this.

Try ``git rebase -i upstream/master`` and then ``git push --force``

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
